### ISSUE TITLE
你会用TDD吗？

### ISSUE THREAD

**Issue by VisualStudioGayHub** [dwyl/learn-tdd#152]
测试代码本身也算另一种形式的业务代码，为了保证测试代码的正确。
你给测试代码写测试吗？
你给测试代码的测试代码写测试吗？
你给测试代码的测试代码的测试代码写测试吗？
你给测试代码的测试代码的测试代码的测试代码写测试吗？
你不写，就代表你不会用TDD，你就写不出高质量代码，你就无法重构代码，你就会被程序界开除人籍

**Comment by iteles** [comment]
As far as I can tell, both from the fact that no effort has been made to write/translate into the language that is clearly used by the community and this repo's maintainers, as well as by what comes up using Google translate, this is not a reasonable or helpful issue. 

@VisualStudioGayHub Please feel free to reformulate and reopen (in English so the community can understand and help, in the case that there is actually a question here).

**Comment by nelsonic** [comment]
Hi @VisualStudioGayHub, 👋 
Thank you for opening this issue to ask a superb question; it’s one that comes up a lot. 💭
We recognise that **`English`** is not the _first_ language for the vast majority of people. 🇬🇧 
And Google Translate [translate.google.com](https://translate.google.com/) may be ***blocked*** where you are. 😞 

![do-you-use-tdd](https://user-images.githubusercontent.com/194400/190965348-9985bb6f-5a78-45a2-ac30-2eb9e38adae1.PNG)

The **_short_ answer** is: **Yes**. ***Absolutely***! We do **Test Driven Development** (**TDD**) as **_much_ as possible**. 👩‍💻 

The **_longer_ answer** is: ***Yes***, we follow the TDD best practice in our day-to-day work because it is a more **systematic** and **scientific** approach to software engineering. 

Skipping writing tests is like a restaurant chef not following a recipe, it can go well _some_ of the time, but the results are inconsistent and will not scale. 

![image](https://user-images.githubusercontent.com/194400/191000699-a09a79da-a353-443a-b902-5e2ed68d3330.png)

Rough translation (care of Google Translate):

```
The test code itself is also another form of business code, 
in order to ensure the correctness of the test code.
Do you write tests for test code?
Do you write tests for the test code of the test code?
Do you write tests for test code for test code for test code?
Do you write tests for test code for test code for test code for test code for test code?
If you don't write it, it means you won't use TDD, you won't be able to write high-quality code, 
you won't be able to refactor the code, and you will be expelled from the programming world.
```

We **100% agree** with what you've written. 💯 👍 


We don't tend to write tests _for_ the tests. 
But we do regularly write test helper functions to simplify/streamline our tests.
The purpose of the test code is to _describe_ the "hypothesis" or desired feature we are building.
Then when the feature code makes the test pass we consider it complete. 

As for the tests for test code for test code ... 🤷‍♂️  and "_expelled from the programming world_" :trollface:  🙄 
Focus on getting [**_really_ good**](https://www.goodreads.com/book/show/13525945-so-good-they-can-t-ignore-you) at what you do before you propose an alternative way of doing things. 👌 
Best of luck with your software engineering career. 🍀 

Dupe of: https://github.com/mjhea0/flaskr-tdd/issues/77, https://github.com/ResoCoder/flutter-tdd-clean-architecture-course/issues/49 and https://github.com/gregmalcolm/python_koans/issues/259
