### ISSUE TITLE
Request: Standard JS

### ISSUE THREAD

**Issue by Peripona** [dwyl/learn-tdd#72]
How about adding standard-js as a Bonus feature as well. 
Following JS Standards from [standardjs](http://standardjs.com)
and getting that StandarJs Following badge for consistency. 

[![js-standard-style](https://img.shields.io/badge/code%20style-standard-brightgreen.svg?style=flat)](http://standardjs.com/)

❇️ ❇️ ❇️ ❇️ ❇️ ❇️ ❇️

**Comment by nelsonic** [comment]
@Peripona (_while we ❤️  your enthusiasm!_) we don't follow "_feross/standard_" 
because it is _not_ "_The_ Standard" its _a_ standard (_i.e. one of **many**_) 
which is used by _some_ people/teams writing JS and should only be _considered_ 
as an `option` if you subscribe to _all_ of its _opinions_ ... 🤔 

Standard encourages use of [`ASI`](http://stackoverflow.com/questions/2846283/what-are-the-rules-for-javascripts-automatic-semicolon-insertion-asi) (_i.e. no semicolons_) which _we have_ seen is not "foolproof" when attempting to debug code at some of the biggest companies... 😢 
**Brendan Eich** the _**creator**_ of `JavaScript` has this to say: https://brendaneich.com/2012/04/the-infernal-semicolon/ 

if you _understand_ the need for using Semicolons, there's [`semistandard`](https://github.com/Flet/semistandard) which is just `"feross/standard with semicolons sprinkled on top"` ... we used it for a few of our projects but then it [_**broke our build**_](https://github.com/Flet/semistandard/issues/111) when a [`non-semver`](http://semver.org/) change was _unexpectedly_added ... so we _decided_ to ***stop wasting time*** ⌛️  on _fickle_ "standards" which don't really offer an _advantage_ to _beginners_ (_who are our "target audience"_) ... :tired_face:

We decided to _create_ an ESLint Config based on `"JavaScript the Good Parts"` 📘 
see: https://github.com/dwyl/goodparts so we could be in _control_ of the rules we use in our project(s). [![JavaScript Style Guide: Good Parts](https://img.shields.io/badge/code%20style-goodparts-brightgreen.svg?style=flat)](https://github.com/dwyl/goodparts "JavaScript The Good Parts") 

Have you had a chance to read `"JavaScript the Good Parts"` ? 💡 
There's a _reason_ it hasn't _left_ the "_Best Seller_" list: https://www.amazon.com/gp/bestsellers/books/3617/ since it was released in **2008**. 📈 
If you can write _more reliable_ code with _fewer_ elements of the _language_ which then means fewer bugs and _cross-platform inconsistencies_, why would want to do it _any_ other way? 😉 
![JavaScript The Good Parts](http://nelsonwells.net/wp-content/uploads/2011/06/javascript_good_and_bad_parts.jpg)

> With [`goodparts`](https://github.com/dwyl/goodparts) you can _sure_ that your code ***Just Works Everywhere All The Time***<sup>TM</sup>
> (_without compilation/"transpilation" or any other "steps" ... you can still minify to reduce bandwidth - using Google Closure Compiler - but this is 100% optional!_)

**Comment by Peripona** [comment]
First of all. 
This morning, I wake up, checking my emails.. and fell in love ❤️ ❤️ with your awesome reply to my request. 
You nailed it. 👍 💯 
to add more sugar on top of it. 
request to join the organization made me feel 🏆 Awesome. 

I don't know if it is by chance or something. I am deeply touched by the sheer simplicity by which you have explained the testing from scratch. both on front end and back end. 
I wish i can also explain some the learnings and contribute to open source community.

I agree with you. it is pain to do `standard --fix ` in case you have contributors to the repo or even if you miss some space somewhere. I right now did not know how to do it with ESlint config bass on javascript good parts. 

Could you update the same on how we can do it with the ESlint config in your learn-tdd Readme.md !! 
would be great 

Thanks

> Note: what a coincidence, I always had my email signature tagline as.. ```Do What you love and Love what you do```  💃 🎤 🎮 😍 💻

**Comment by nelsonic** [comment]
Closing. see: https://github.com/dwyl/goodparts 👍
